= Developer Guide

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc-placement: preamble
endif::[]


== Builder

ifdef::env-github[]
== Builder Class diagram
image::diagrams/builder-class-diagram.svg[alt="Builder Class Diagram", max-width=1024]

== Http Builder Class diagram
image::diagrams/http-builder-class-diagram.svg[alt="Builder Class Diagram", max-width=1024]

== HttpClient Class diagram
image::diagrams/http-client-class-diagram.svg[alt="Builder Class Diagram", max-width=1024]

endif::[]

ifndef::env-github[]
== Builder Class diagram
plantuml::puml/builder-class-diagram.puml[format=svg, alt="Builder Class Diagram", max-width=1024]

== Http Builder Class diagram
plantuml::puml/http-builder-class-diagram.puml[format=svg, alt="Builder Class Diagram", max-width=1024]

== HttpClient Class diagram
plantuml::puml/http-client-class-diagram.puml[format=svg, alt="Builder Class Diagram", max-width=1024]

endif::[]
